apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: weather-api-monitor
  labels:
    release: monitoring 
spec:
  selector:
    matchLabels:
      app: weather-api  
  endpoints:
  - port: http          
    interval: 30s
    path: /metrics
